/**
 * PharmaSys — License Generator (Developer Tool)
 *
 * Run this tool to issue a license for a specific client device.
 * Requires tools/PRIVATE_KEY.pem (generated by generate-keypair.js).
 *
 * Usage:
 *   node tools/generate-license.js
 *   → Edit the CLIENT_CONFIG section below before running.
 *
 * Output:
 *   <ClientName>-Device<N>.pharmalicense
 *   → Send this file to the client via email/USB/WhatsApp.
 *
 * The client imports this file in the app's "Activation Required" screen.
 *
 * WORKFLOW:
 *   1. Client installs PharmaSys → app shows their Machine ID (e.g. "A3F2B7C1")
 *   2. Client sends you that Machine ID
 *   3. Edit CLIENT_CONFIG below with their name and Machine ID
 *   4. Run: node tools/generate-license.js
 *   5. Send the output .pharmalicense file to the client
 *   6. Client clicks "Import License File" in the app → activated!
 */

const crypto = require('crypto');
const fs     = require('fs');
const path   = require('path');

// ── EDIT THIS SECTION FOR EACH NEW CLIENT ────────────────────────────────────
const CLIENT_CONFIG = {
  clientName:  'PharmaSys Dev',              // Client's name (for your records)
  machineId:   '6BD18079-0BDB627C-CCE4B3CE-49DDB133', // From their app screen
  expiresAt:   null,                         // null = perpetual. Or: '2027-03-01'
  maxDevices:  1,                            // Total devices this client has
  deviceIndex: 1,                            // Which device this file is for (1, 2, 3...)
};
// ─────────────────────────────────────────────────────────────────────────────

function generateLicense(config) {
  const privKeyPath = path.join(__dirname, 'PRIVATE_KEY.pem');

  if (!fs.existsSync(privKeyPath)) {
    console.error('ERROR: tools/PRIVATE_KEY.pem not found.');
    console.error('Run: node tools/generate-keypair.js');
    process.exit(1);
  }

  const PRIVATE_KEY = fs.readFileSync(privKeyPath, 'utf-8');

  const payload = {
    clientName:  config.clientName,
    machineId:   config.machineId,
    issuedAt:    new Date().toISOString().slice(0, 10),
    expiresAt:   config.expiresAt ?? null,
    maxDevices:  config.maxDevices,
    deviceIndex: config.deviceIndex,
  };

  const sign      = crypto.createSign('SHA256');
  sign.update(JSON.stringify(payload));
  const signature = sign.sign(PRIVATE_KEY, 'base64');

  return JSON.stringify({ payload, signature }, null, 2);
}

const licenseJson = generateLicense(CLIENT_CONFIG);

// Sanitise client name for filename
const safeName    = CLIENT_CONFIG.clientName.replace(/[^a-zA-Z0-9_-]/g, '_');
const outputFile  = path.join(
  __dirname,
  `${safeName}-Device${CLIENT_CONFIG.deviceIndex}.pharmalicense`
);

fs.writeFileSync(outputFile, licenseJson);

console.log('');
console.log('✅ License generated successfully!');
console.log('');
console.log(`  Client:   ${CLIENT_CONFIG.clientName}`);
console.log(`  Machine:  ${CLIENT_CONFIG.machineId}`);
console.log(`  Expires:  ${CLIENT_CONFIG.expiresAt ?? 'Never (perpetual)'}`);
console.log(`  Device:   ${CLIENT_CONFIG.deviceIndex} of ${CLIENT_CONFIG.maxDevices}`);
console.log(`  File:     ${outputFile}`);
console.log('');
console.log('→ Send this file to the client.');
console.log('→ They import it in the "Activation Required" screen.');
