/**
 * PharmaSys — License Validator
 *
 * Verifies ECDSA P-256 signature, machine ID binding, and expiry.
 * All checks are offline — no internet connection required.
 *
 * The PUBLIC_KEY below is the counterpart to tools/PRIVATE_KEY.pem.
 * If you regenerate the key pair (tools/generate-keypair.js), replace this constant
 * with the new PUBLIC_KEY.pem content and rebuild the app.
 */

import * as crypto from 'crypto';
import { getMachineId, getMachineIdAsync } from './machine-id';

// ── EMBEDDED PUBLIC KEY ───────────────────────────────────────────────────────
// Generated by tools/generate-keypair.js — safe to distribute in the app.
// Private key stays in tools/PRIVATE_KEY.pem (never committed to git).
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEN75X/ocJf+sUKJU0DWgjDOBgaXqN
HHT56nr9ZYMaDe10pumUpEpz/zUecFzmyOkTCAf0t2/Ma+jSKpfmGaHKLw==
-----END PUBLIC KEY-----`;
// ─────────────────────────────────────────────────────────────────────────────

export interface LicensePayload {
  clientName:  string;
  machineId:   string;
  issuedAt:    string;
  expiresAt:   string | null; // ISO date string, or null = never expires
  maxDevices:  number;
  deviceIndex: number;
}

export interface LicenseResult {
  valid:    boolean;
  reason?:  string;
  payload?: LicensePayload;
}

/**
 * Validate a license JSON string.
 * Returns { valid: true, payload } on success, or { valid: false, reason } on failure.
 */
export function validateLicense(licenseJson: string): LicenseResult {
  try {
    const parsed = JSON.parse(licenseJson) as { payload: LicensePayload; signature: string };
    const { payload, signature } = parsed;

    // 1 — Cryptographic signature check
    const verify = crypto.createVerify('SHA256');
    verify.update(JSON.stringify(payload));
    const signatureOk = verify.verify(PUBLIC_KEY, signature, 'base64');

    if (!signatureOk) {
      return {
        valid:  false,
        reason: 'License signature is invalid. The file may be tampered with. Contact your vendor.',
      };
    }

    // 2 — Machine ID binding check
    const currentId = getMachineId();
    if (payload.machineId !== currentId) {
      return {
        valid:  false,
        reason: `This license is issued for a different device. Contact your vendor to transfer the license.`,
      };
    }

    // 3 — Expiry check
    if (payload.expiresAt) {
      const expiry = new Date(payload.expiresAt);
      if (expiry < new Date()) {
        return {
          valid:  false,
          reason: `License expired on ${payload.expiresAt}. Contact your vendor to renew.`,
        };
      }
    }

    return { valid: true, payload };

  } catch {
    return {
      valid:  false,
      reason: 'License file is corrupted or in an unrecognised format. Please reimport the file.',
    };
  }
}

/**
 * Async version of validateLicense — uses getMachineIdAsync() so it never
 * blocks the Electron main process during startup.
 */
export async function validateLicenseAsync(licenseJson: string): Promise<LicenseResult> {
  try {
    const parsed = JSON.parse(licenseJson) as { payload: LicensePayload; signature: string };
    const { payload, signature } = parsed;

    const verify = crypto.createVerify('SHA256');
    verify.update(JSON.stringify(payload));
    const signatureOk = verify.verify(PUBLIC_KEY, signature, 'base64');

    if (!signatureOk) {
      return {
        valid:  false,
        reason: 'License signature is invalid. The file may be tampered with. Contact your vendor.',
      };
    }

    const currentId = await getMachineIdAsync();
    if (payload.machineId !== currentId) {
      return {
        valid:  false,
        reason: 'This license is issued for a different device. Contact your vendor to transfer the license.',
      };
    }

    if (payload.expiresAt) {
      const expiry = new Date(payload.expiresAt);
      if (expiry < new Date()) {
        return {
          valid:  false,
          reason: `License expired on ${payload.expiresAt}. Contact your vendor to renew.`,
        };
      }
    }

    return { valid: true, payload };

  } catch {
    return {
      valid:  false,
      reason: 'License file is corrupted or in an unrecognised format. Please reimport the file.',
    };
  }
}
